spring.application.name=cloudStudy
server.port=8080

logging.level.org.springframework=info
logging.level.org.springframework.web=info

# 로그 파일 저장 설정
logging.file.name=logs/app.log

# JWT 설정
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION}

# Database Setting
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA Setting
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Redis 설정
spring.data.redis.host=localhost
spring.data.redis.port=6379

